# Generated by Django 2.2.12 on 2020-04-29 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_currency', models.CharField(choices=[('btc', 'BTC')], max_length=3)),
                ('dest_currency', models.CharField(choices=[('usd', 'USD')], max_length=3)),
                ('price', models.FloatField()),
                ('rate_updated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
